version: "3"

services:
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
  db:
    container_name: db
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=my_database
    ports:
      - "5432:5432"
    healthcheck:
      test: exit 0
  service:
    build: ./user-management-service
    container_name: service
    ports:
      - "3000:3000"
    depends_on: 
      - db