export enum Configuration {
    PORT="PORT",

    DB_DIALECT="DB_DIALECT",
    DB_HOST="DB_HOST",
    DB_PORT="DB_PORT",
    DB_USER="DB_USER",
    DB_PASS="DB_PASS",
    DB_DATABASE="DB_DATABASE",

    APP_KEY="APP_KEY",

    REDIS_HOST="REDIS_HOST",
    REDIS_PORT="REDIS_PORT",
    REDIS_TTL="REDIS_TTL"
}